// <auto-generated />
using HCRUDEasy.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HCRUDEasy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20170922190819_Primeiro")]
    partial class Primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HCRUDEasy.Domain.Bank.BankInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<string>("AccountType");

                    b.Property<string>("Agency");

                    b.Property<string>("BankName");

                    b.Property<string>("Cpf");

                    b.Property<string>("PersonName");

                    b.HasKey("Id");

                    b.ToTable("BankInformation");
                });

            modelBuilder.Entity("HCRUDEasy.Domain.Person.Candidate.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BankInformationId");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.HasIndex("BankInformationId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("HCRUDEasy.Domain.Person.Candidate.Candidate", b =>
                {
                    b.HasOne("HCRUDEasy.Domain.Bank.BankInformation", "BankInformation")
                        .WithMany()
                        .HasForeignKey("BankInformationId");
                });
#pragma warning restore 612, 618
        }
    }
}
